# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8099
  servlet:
    context-path: /api

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/note?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5

# mapper映射扫描
# myBatis-plus
mybatis-plus:
  # 扫描包来让mybatis自动扫描到自定义
  type-aliases-package: watcher.cloud.entity
  #映射路径拼接
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 下划线自动转驼峰
    map-underscore-to-camel-case: true
    # 展示日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
